# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/TrailingComma:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/DotPosition:
  EnforcedStyle: trailing

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/PerlBackrefs:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented


Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable
